apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-helm-chart.fullname" . }}
  labels:
    app: {{ include "my-helm-chart.name" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
      nodePort:  {{ .Values.service.nodePort }}
  selector:
    app: {{ include "my-helm-chart.name" . }}
