apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-helm-chart
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/AmanSingh881/GitOps-ArgoCD-Project.git'
    targetRevision: main
    path: my-helm-chart
  destination:
    server: https://kubernetes.default.svc
    namespace: my-helm-app
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
